/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ua.com.alevel.form;

import ua.com.alevel.service.ReverseStringService;

/**
 *
 * @author pozna
 */
public class ReverseStringForm extends javax.swing.JFrame {

    private final ReverseStringService reverseStringService;

    public ReverseStringForm(ReverseStringService reverseStringService) {
        this.reverseStringService = reverseStringService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        textInputField = new javax.swing.JTextField();
        getResultBtn = new javax.swing.JButton();
        wellcomeLabel = new javax.swing.JLabel();
        allStringReversedCheckBox = new javax.swing.JCheckBox();
        charSequenceInputField = new javax.swing.JTextField();
        reverseByCharSequenceLabel = new javax.swing.JLabel();
        charSequenceRadioButton = new javax.swing.JRadioButton();
        indexRadioButton = new javax.swing.JRadioButton();
        indexLabel = new javax.swing.JLabel();
        stringEnteredLabel = new javax.swing.JLabel();
        justReverseRadioButton = new javax.swing.JRadioButton();
        justReverseLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        resultLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        getResultBtn.setText("Get result");
        getResultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getResultBtnActionPerformed(evt);
            }
        });

        wellcomeLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 30)); // NOI18N
        wellcomeLabel.setForeground(new java.awt.Color(217, 30, 133));
        wellcomeLabel.setText("Hello, user");

        allStringReversedCheckBox.setText("Reversed by words ?");

        reverseByCharSequenceLabel.setText("Enter below the part of the string you want to reverse ");

        buttonGroup1.add(charSequenceRadioButton);

        buttonGroup1.add(indexRadioButton);

        indexLabel.setText("Enter 2 indexes separated by commas, starting with which and ending with which, the string will be reversed");

        stringEnteredLabel.setText("Enter the string below:");

        buttonGroup1.add(justReverseRadioButton);

        justReverseLabel.setText("Just reverse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(wellcomeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(charSequenceInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allStringReversedCheckBox)
                            .addComponent(resultLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(indexRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(indexLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(charSequenceRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reverseByCharSequenceLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(getResultBtn))
                            .addComponent(stringEnteredLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(justReverseRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(justReverseLabel))
                            .addComponent(resultLabel1))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wellcomeLabel)
                .addGap(26, 26, 26)
                .addComponent(allStringReversedCheckBox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(justReverseRadioButton)
                    .addComponent(justReverseLabel))
                .addGap(11, 11, 11)
                .addComponent(resultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(charSequenceRadioButton)
                    .addComponent(reverseByCharSequenceLabel))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(indexRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(charSequenceInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(indexLabel))
                .addGap(17, 17, 17)
                .addComponent(stringEnteredLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getResultBtn))
                .addGap(18, 18, 18)
                .addComponent(resultLabel1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getResultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getResultBtnActionPerformed
        String result = "";
        if (charSequenceRadioButton.isSelected()) {

        } else if (indexRadioButton.isSelected()) {
            String[] indexes = charSequenceInputField.getText().split(",");
            Integer firstIndex = Integer.valueOf(indexes[0]);
            Integer lastIndex = Integer.valueOf(indexes[1]);
            result = this.reverseStringService.reverse(textInputField.getText(), firstIndex, lastIndex, !allStringReversedCheckBox.isSelected());
        } else {
            result = this.reverseStringService.reverse(textInputField.getText(), !allStringReversedCheckBox.isSelected());
        }
        resultLabel1.setText(result);
    }//GEN-LAST:event_getResultBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allStringReversedCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField charSequenceInputField;
    private javax.swing.JRadioButton charSequenceRadioButton;
    private javax.swing.JButton getResultBtn;
    private javax.swing.JLabel indexLabel;
    private javax.swing.JRadioButton indexRadioButton;
    private javax.swing.JLabel justReverseLabel;
    private javax.swing.JRadioButton justReverseRadioButton;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel resultLabel1;
    private javax.swing.JLabel reverseByCharSequenceLabel;
    private javax.swing.JLabel stringEnteredLabel;
    private javax.swing.JTextField textInputField;
    private javax.swing.JLabel wellcomeLabel;
    // End of variables declaration//GEN-END:variables
}
